(defun make-accumulator ()
  (let ((items nil))
    (lambda (x)
      (setq items (append items (list x)))
      items)))
(defvar *acc* (make-accumulator))
(print (funcall *acc* "a"))
(print (funcall *acc* "b"))
(print (funcall *acc* "c"))