(defun make-counter (start)
  (let ((count start))
    (lambda ()
      (setq count (+ count 1))
      count)))
(defvar *c* (make-counter 10))
(print (funcall *c*))
(print (funcall *c*))
(print (funcall *c*))