(defun fizzbuzz (n)
  (cond
    ((zerop (mod n 15)) "FizzBuzz")
    ((zerop (mod n 3)) "Fizz")
    ((zerop (mod n 5)) "Buzz")
    (t n)))
(print (fizzbuzz 15))
(print (fizzbuzz 9))
(print (fizzbuzz 10))
(print (fizzbuzz 7))